core/urls.py
from django.conf.urls import url
from .views import buscar_cidades

urlpatterns = [
    url(r'^buscar-cidades/$', buscar_cidades, name='buscar_cidades'),
]

dashboard/urls.py
from django.conf.urls import url
from .views import dashboard
from django.views.generic import TemplateView

urlpatterns = [
    url(r'^$', dashboard, name='dashboard'),
]

finxi_imoveis/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.contrib.auth.views import logout_then_login, login


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^login/$', login, {"template_name": 'website/login.html'}, name='login'),
    url(r'^logout/', logout_then_login, {'login_url': '/'}, name='logout'),
    url(r'^', include('website.urls', namespace='website')),
    url(r'^imoveis/', include('imoveis.urls', namespace='imoveis')),
    url(r'^dashboard/', include('dashboard.urls', namespace='dashboard')),
    url(r'^core/', include('core.urls', namespace='core')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

imoveis/urls.py
from django.conf.urls import url
from django.contrib import admin

from .views import lista_de_imoveis, novo_imovel, editar_imovel, detalhes

urlpatterns = [
    url(r'^$', lista_de_imoveis, name='lista_de_imoveis'),
    url(r'^novo/$', novo_imovel, name='novo_imovel'),
    url(r'^(?P<pk>[0-9]+)/editar/$', editar_imovel, name='editar_imovel'),
    url(r'^(?P<pk>[0-9]+)/info/$', detalhes, name='detalhes'),
]

website/urls.py
from django.conf.urls import url
from django.contrib import admin

from .views import index, ProcurarImoveis

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^procurar/$', ProcurarImoveis.as_view(), name='procurar'),
]

core/models.py
from django.db import models


class TimeStampedModel(models.Model):
    created = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    modified = models.DateTimeField(auto_now=True, blank=True, null=True)

    class Meta:
        abstract = True

class UF(models.Model):
    '''
        @UF: Data model with all states
    '''
    cod   = models.IntegerField(unique=True)
    sigla = models.CharField(max_length=2)
    name  = models.CharField(max_length=50)
    

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']
        db_table = u'uf'


class Cidade(models.Model): 
    '''
        @City: Data model with all cities.
    '''           
    federativa  = models.ForeignKey(UF, related_name='cidades')
    cod         = models.IntegerField(unique=True)
    name        = models.CharField(max_length=70)
    cep_inicial = models.IntegerField(unique=True)
    cep_final   = models.IntegerField(unique=True)
    ddd1        = models.IntegerField()
    ddd2        = models.IntegerField()
    
    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']
        db_table = u'cidade'

core/views.py
from django.http import JsonResponse
from django.shortcuts import render
from .models import UF, Cidade

def buscar_cidades(request):
    if 'estado' in request.GET:
        estado = request.GET.get('estado')
        queryset = list(Cidade.objects.filter(federativa__pk=estado).values('id', 'name'))
    else:
        queryset = list(Cidade.objects.none())
    return JsonResponse(queryset, safe=False)

core/templates/includes/footer.html
{% load staticfiles %}

<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>

<!-- Bootstrap Core JavaScript -->
<script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>

<!-- Metis Menu Plugin JavaScript -->
<script src="{% static 'vendor/metisMenu/metisMenu.min.js' %}"></script>

<!-- Custom Theme JavaScript -->
<script src="{% static 'dist/js/sb-admin-2.js' %}"></script>

<script src="{% static 'js/search_cep.js' %}"></script>

core/templates/includes/header.html
{% load staticfiles %}
<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Finxi Imóveis</title>

    <!-- Bootstrap Core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- MetisMenu CSS -->
    <link href="{% static 'vendor/metisMenu/metisMenu.min.css' %}" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{% static 'dist/css/sb-admin-2.css' %}" rel="stylesheet">

    <!-- Morris Charts CSS -->
    <link href="{% static 'vendor/morrisjs/morris.css' %}" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="{% static 'vendor/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

core/templates/includes/menu.html
<div id="wrapper">
    <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
        <div class="navbar-header">
            <a class="navbar-brand" href="{% url 'website:index' %}">Finxi Imóveis</a>
        </div>
        {% if request.user.is_authenticated %}
            <ul class="nav navbar-top-links navbar-right">
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-user fa-fw"></i> <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-user">
                        <!-- <li><a href="#"><i class="fa fa-user fa-fw"></i> User Profile</a>
                        </li>
                        <li><a href="#"><i class="fa fa-gear fa-fw"></i> Settings</a>
                        </li> -->
                        <li class="divider"></li>
                        <li><a href="{% url 'logout' %}"><i class="fa fa-sign-out fa-fw"></i> Logout</a>
                        </li>
                    </ul>
                </li>
            </ul>
        {% else %}
            <ul class="nav navbar-top-links navbar-right">
                <li>
                    <a href="{% url 'login' %}">Login</a>
                </li>
            </ul>
        {% endif %}
        <div class="navbar-default sidebar" role="navigation">
            <div class="sidebar-nav navbar-collapse">
                <ul class="nav" id="side-menu">
                    
                        
                    {% if request.user.is_authenticated %}
                        <li>
                            <a href="{% url 'dashboard:dashboard' %}"><i class="fa fa-dashboard fa-fw"></i> Dashboard</a>
                        </li>
                        <li>
                            <a href="{% url 'imoveis:lista_de_imoveis' %}"><i class="fa fa-tasks fa-fw"></i> Imóveis</a>
                        </li>
                    {% else %}
                        <li class="sidebar-search">
                            <div class="input-group custom-search-form">
                                <form method="GET" action="{% url 'website:procurar' %}">
                                    <div class="form-group">
                                        Estado: {{ form_search.estado }}
                                    </div>
                                    <div class="form-group">
                                        Cidade: {{ form_search.cidade }}
                                    </div>
                                    <div class="form-group">
                                        Bairro: {{ form_search.bairro }}
                                    </div>
                                    <br><br>
                                    <div class="form-group">
                                        <input type="submit" class="btn btn-success" value="Pesquisar"/>
                                    </div>
                                </form>
                            </div>
                            <!-- /input-group -->
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
</div>