core/urls.py
from django.conf.urls import url
from .views import buscar_cidades

urlpatterns = [
    url(r'^buscar-cidades/$', buscar_cidades, name='buscar_cidades'),
]

dashboard/urls.py
from django.conf.urls import url
from .views import dashboard
from django.views.generic import TemplateView

urlpatterns = [
    url(r'^$', dashboard, name='dashboard'),
]

finxi_imoveis/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.contrib.auth.views import logout_then_login, login


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^login/$', login, {"template_name": 'website/login.html'}, name='login'),
    url(r'^logout/', logout_then_login, {'login_url': '/'}, name='logout'),
    url(r'^', include('website.urls', namespace='website')),
    url(r'^imoveis/', include('imoveis.urls', namespace='imoveis')),
    url(r'^dashboard/', include('dashboard.urls', namespace='dashboard')),
    url(r'^core/', include('core.urls', namespace='core')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

imoveis/urls.py
from django.conf.urls import url
from django.contrib import admin

from .views import lista_de_imoveis, novo_imovel, editar_imovel, detalhes

urlpatterns = [
    url(r'^$', lista_de_imoveis, name='lista_de_imoveis'),
    url(r'^novo/$', novo_imovel, name='novo_imovel'),
    url(r'^(?P<pk>[0-9]+)/editar/$', editar_imovel, name='editar_imovel'),
    url(r'^(?P<pk>[0-9]+)/info/$', detalhes, name='detalhes'),
]

imoveis/models.py
import json
from django.db import models
from django.db.models.signals import post_save
from django.conf import settings
from django.urls import reverse
from core.models import TimeStampedModel
from core.utils import BuscarLatitudeLongitude

import requests
from easy_thumbnails.fields import ThumbnailerImageField


class Imovel(TimeStampedModel):
    titulo = models.CharField('Título', max_length=255)
    descricao = models.TextField()
    cep = models.CharField('Cep', max_length=255)
    rua = models.CharField('Rua', max_length=255)
    numero = models.CharField('Número', max_length=10)
    complemento = models.CharField('Complemento', max_length=255, blank=True, null=True)
    bairro = models.CharField('Bairro', max_length=255)
    cidade = models.ForeignKey('core.Cidade')
    estado = models.ForeignKey('core.UF')
    telefone1 = models.CharField(max_length=20)
    telefone2 = models.CharField(max_length=20, blank=True, null=True)
    proprietario = models.CharField(max_length=255)
    foto = ThumbnailerImageField(upload_to='fotos/', resize_source=dict(size=(150, 150)))
    latitude = models.DecimalField(max_digits=9, decimal_places=6, blank=True, null=True)
    longitude = models.DecimalField(max_digits=9, decimal_places=6, blank=True, null=True)
    ativo = models.BooleanField(default=True)

    def __str__(self):
        return self.titulo

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        manager = BuscarLatitudeLongitude(self.rua, self.cidade.name, self.estado.name)
        latitude, longitude = manager.get_latitude_longitude()
        self.latitude = latitude
        self.longitude = longitude
        super(Imovel, self).save(force_insert=False, force_update=False, 
            using=None, update_fields=None)

    def get_absolute_url(self):
        return reverse('imoveis:editar_imovel', kwargs={'pk': self.pk})

    def get_detail_url(self):
        return reverse('imoveis:detalhes', kwargs={'pk': self.pk})       

class Foto(TimeStampedModel):
    foto = models.ImageField(upload_to='fotos/')
    imovel = models.ForeignKey('Imovel', related_name='fotos')

imoveis/forms.py
from django import forms
from django.forms.models import inlineformset_factory

from .models import Imovel, Foto

class ImovelForm(forms.ModelForm):
    fotos = forms.FileField(label='Fotos', 
        widget=forms.FileInput(attrs={'multiple':True}), required=False)

    class Meta:
        model = Imovel
        fields = [
            'titulo',
            'descricao',
            'cep',
            'rua',
            'numero',
            'complemento',
            'bairro',
            'cidade',
            'estado',
            'telefone1',
            'telefone2',
            'proprietario',
            'foto',
        ]
        widgets = {
            'titulo': forms.TextInput(attrs={'class': 'form-control'}), 
            'descricao': forms.Textarea(attrs={'class': 'form-control'}),

            'cep': forms.TextInput(attrs={'class': 'form-control zip_code', 
                'placeholder': 'Cep'}),
            'rua':forms.TextInput(attrs={'class': 'form-control', 'readonly':True}),
            'numero':forms.TextInput(attrs={'class': 'form-control'}),
            'complemento':forms.TextInput(attrs={'class': 'form-control'}),
            'bairro':forms.TextInput(attrs={'class': 'form-control', 'readonly':True}),
            'cidade':forms.Select(attrs={'class': 'form-control', 'readonly':True}),
            'estado':forms.Select(attrs={'class': 'form-control', 'readonly':True}),
            'telefone1':forms.TextInput(attrs={'class': 'form-control'}),
            'telefone2':forms.TextInput(attrs={'class': 'form-control'}),
            'proprietario':forms.TextInput(attrs={'class': 'form-control'}),
        }

class FotoForm(forms.ModelForm):

    class Meta:
        model = Foto
        fields = ['foto',]

FotoFormSet = inlineformset_factory(Imovel, Foto, form=FotoForm, extra=0)

imoveis/views.py
from django.core.urlresolvers import reverse as r
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404

from .forms import ImovelForm, FotoFormSet
from .models import Imovel, Foto

@login_required
def lista_de_imoveis(request):
    imoveis = Imovel.objects.all()
    return render(request, 'imoveis/lista.html', {'imoveis':imoveis})

@login_required
def novo_imovel(request):

    if request.method == 'POST':
        form = ImovelForm(request.POST, request.FILES)
        if form.is_valid():
            imovel = form.save()
            for f in request.FILES.getlist('fotos'):
                Foto.objects.create(imovel=imovel, foto=f)

            return HttpResponseRedirect(r('imoveis:lista_de_imoveis'))
    else:
        form = ImovelForm()

    return render(request,'imoveis/novo.html', {'form':form})


@login_required
def editar_imovel(request, pk):
    imovel = get_object_or_404(Imovel, pk=pk)
    if request.method == 'POST':
        form = ImovelForm(request.POST, request.FILES, instance=imovel)
        formset = FotoFormSet(request.POST, request.FILES, instance=imovel)
        if form.is_valid() and formset.is_valid():
            imovel = form.save()
            formset.save()
            for f in request.FILES.getlist('fotos'):
                Foto.objects.create(imovel=imovel, foto=f)
            return HttpResponseRedirect(r('imoveis:lista_de_imoveis'))
    else:
        form = ImovelForm(instance=imovel)
        formset = FotoFormSet(instance=imovel)
    return render(request, 'imoveis/editar.html', 
        {'form':form, 'formset':formset})

def detalhes(request, pk):
    imovel = get_object_or_404(Imovel, pk=pk)
    return render(request, 'imoveis/detalhes.html', {'imovel':imovel})

imoveis/templates/imoveis/detalhes.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}

    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">{{ imovel.titulo }}</h1>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            
            {{ imovel.descricao }}

            <br>

            Bairro: {{ imovel.bairro }}<br>
            {{ imovel.cidade|title }} - {{ imovel.estado.sigla }}<br>
            Cep: {{ imovel.cep }}<br>
                                    
            Telefone 01: {{ imovel.telefone1 }}<br>
            Telefone 02: {{ imovel.telefone2|default:"" }}<br>
            Proprietário: {{ imovel.proprietario }}<br><br>

            {% for obj in imovel.fotos.all %}
                <img src="{{ obj.foto.url }}" style="width: 200px;margin-bottom: 20px;"/> 
            {% endfor%}
        </div>
    </div>
{% endblock %}

imoveis/templates/imoveis/editar.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}

    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Editar Imóvel</h1>
        </div>
    </div>
        <div class="row">
            <div class="col-lg-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <a href="{% url 'dashboard:dashboard' %}">Home</a> / 
                        <a href="{% url 'imoveis:lista_de_imoveis' %}">Imóveis</a> / 
                        <a>Editar Imóvel</a>
                    </div>
                    <div class="panel-body">
                        <form role="form" method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="row">
                                <div class="col-lg-12">
                                    {{ form.as_p }}
                                </div>
                                <div class="col-lg-12">
                                    {{ formset.management_form }}
                                    {% for form in formset %}
                                    
                                        {{ form.id }}
                                        {{ form.as_p }}
                                    {% endfor %}
                                    <button type="submit" class="btn btn-primary">Salvar</button>
                                    <button type="reset" class="btn btn-danger">Limpar Alterações</button>
                                </div>

                            </div>

                        </form>
                    </div>
                </div>
            </div>
        </div>
{% endblock %}




{% block extra_js %}
    <script src="{% static 'js/search_cep.js' %}"></script>
{% endblock %}

imoveis/templates/imoveis/lista.html
{% extends 'base.html' %}

{% block content %}
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Imóveis</h1>
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <a href="{% url 'imoveis:novo_imovel' %}" class="btn btn-primary">Novo Imóvel</a>
    <br><br>
        <!-- /.row -->
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Lista de imóveis
                </div>
                <!-- /.panel-heading -->
                <div class="panel-body">
                    <table width="100%" class="table table-striped table-bordered table-hover" id="dataTables-example">
                        <thead>
                            <tr>
                                <th>Editar</th>
                                <th>Título</th>
                                <th>Proprietário</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for imovel in imoveis %}
                                <tr class="">
                                    <td class="center">
                                        <a href="{{ imovel.get_absolute_url }}">
                                            Editar
                                        </a>
                                    </td>
                                    <td>{{ imovel.titulo }}</td>
                                    <td>{{ imovel.proprietario }}</td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                <!-- /.panel-body -->
            </div>
            <!-- /.panel -->
        </div>
        <!-- /.col-lg-12 -->
    </div>
{% endblock %}

imoveis/templates/imoveis/novo.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}

    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Novo Imóvel</h1>
        </div>
    </div>
        <div class="row">
            <div class="col-lg-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <a href="{% url 'dashboard:dashboard' %}">Home</a> / 
                        <a href="{% url 'imoveis:lista_de_imoveis' %}">Imóveis</a> / 
                        <a>Novo Imóvel</a>
                    </div>
                    <div class="panel-body">
                        <form role="form" method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="row">
                                <div class="col-lg-12">
                                    {{ form.as_p }}
                                    <button type="submit" class="btn btn-primary">Salvar</button>
                                    <button type="reset" class="btn btn-danger">Limpar Alterações</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
{% endblock %}




{% block extra_js %}
    <script src="{% static 'js/search_cep.js' %}"></script>
{% endblock %}